llms:
  # colsed-source:
  #   openai:
  llm_use: groq
  groq:
    text_llm: 
      model: llama-3.2-3b-preview
      config:
        # max_tokens: 100
        temperature: 0.1
    voice_llm: 
      model: whisper-large-v3-turbo
      config:
  huggingface:
    text_llm: 
      model_name: "meta-llama/Llama-3.2-3B" 
      config:
        quantization_config: 
          load_in_4bit: true
          bnb_4bit_quant_type: "nf4"
          bnb_4bit_use_double_quant: true
          bnb_4bit_compute_dtype: torch.bfloat16 
          llm_int8_threshold: 6.0
          llm_int8_skip_modules: ["lm_head"]
        max_new_tokens: 100
        temperature: 0.1
    voice_llm: 
      model_name: "openai/whisper-small"
      config:
    
app:
  graphs:
    skills_training:
      topic_categories:
        impromptu_categories:
          - Ethics and Philosophy
          - Social Issues
          - Technology and Innovation
          - Leadership and Teamwork
          - Personal Development
          - General Knowledge
        story_categories:
          - Personal Growth
          - Adventure
          - Cultural Experience
          - Professional Journey
          - Overcoming Challenges
        conflict_categories:
          - Workplace/Professional
          - Family Dynamics
          - Community/Social
          - Personal Relationships
          - Educational/Academic
graph:
  recursion_limit: 50
